### PR TITLE
Add Plotly color map

### PR DESCRIPTION
**Pull request by appleparan**
I have added a unique color map in Plotly.

* [Reference](https://plotly.com/python/builtin-colorscales/)

### CODE REVIEW

**Comment by appleparan** [comment]
FYI, `urubu` (for docs) seems to be a dead project. I had following issues when generating docs.

1. [`markdown` should be `< 3`](https://github.com/jandecaluwe/urubu-quickstart/issues/10)
2. [Need `index.md` even it is ignored](https://github.com/jandecaluwe/urubu/issues/35)

**Comment by jiffyclub** [comment]
Looks cool, thank you! Could you please also add a test here: https://github.com/jiffyclub/palettable/blob/master/test/test_installed.py

> FYI, urubu (for docs) seems to be a dead project. I had following issues when generating docs.

Thanks for the heads up. It was always a pretty small project and I set that up long ago. I'll have to look into a more modern setup.

**Comment by appleparan** [comment]
I added the test.

**Comment by jiffyclub** [comment]
Looks good, thank you!

**Pull request merged**
